import type { Command, Option } from '@commander-js/extra-typings';

export interface OptionNode {
  long?: string;
  short?: string;
  description: string;
  takesValue: boolean;
  choices?: string[];
}

export interface CommandNode {
  name: string;
  aliases: string[];
  description: string;
  subcommands: CommandNode[];
  options: OptionNode[];
}

export function collectCommandTree(cmd: Command): CommandNode {
  const subcommands: CommandNode[] = [];
  for (const sub of cmd.commands) {
    const hidden = (sub as unknown as { _hidden?: boolean })._hidden;
    if (hidden) {
      continue;
    }
    subcommands.push(collectCommandTree(sub as Command));
  }

  const options: OptionNode[] = [];
  for (const opt of cmd.options as Option[]) {
    if (opt.hidden) {
      continue;
    }
    options.push({
      long: opt.long,
      short: opt.short,
      description: opt.description,
      takesValue: opt.required || opt.optional,
      choices: opt.argChoices,
    });
  }

  return {
    name: cmd.name(),
    aliases: cmd.aliases(),
    description: cmd.description(),
    subcommands,
    options,
  };
}

type FlatEntry = {
  path: string;
  subcommands: { name: string; description: string }[];
  options: OptionNode[];
};

function flattenTree(
  node: CommandNode,
  parentPath: string,
  globalOptions: OptionNode[],
): FlatEntry[] {
  const path = parentPath ? `${parentPath} ${node.name}` : node.name;
  const entries: FlatEntry[] = [];

  const subcommands: { name: string; description: string }[] = [];
  for (const sub of node.subcommands) {
    subcommands.push({ name: sub.name, description: sub.description });
    for (const alias of sub.aliases) {
      subcommands.push({ name: alias, description: sub.description });
    }
  }

  const allOptions = [...node.options, ...globalOptions];

  entries.push({ path, subcommands, options: allOptions });

  for (const sub of node.subcommands) {
    entries.push(...flattenTree(sub, path, globalOptions));
  }

  return entries;
}

function collectValueFlags(node: CommandNode): string[] {
  const flags = new Set<string>();
  function walk(n: CommandNode) {
    for (const opt of n.options) {
      if (opt.takesValue) {
        if (opt.long) {
          flags.add(opt.long);
        }
        if (opt.short) {
          flags.add(opt.short);
        }
      }
    }
    for (const sub of n.subcommands) {
      walk(sub);
    }
  }
  walk(node);
  return [...flags];
}

// --- Bash ---

export function generateBashCompletion(tree: CommandNode): string {
  const globalOpts = tree.options;
  const entries = flattenTree(tree, '', []);
  const childEntries = entries.slice(1);

  const choiceOptions: Map<string, string[]> = new Map();
  for (const entry of entries) {
    for (const opt of entry.options) {
      if (opt.choices && opt.long) {
        choiceOptions.set(opt.long, opt.choices);
      }
    }
  }

  const lines: string[] = [];
  const name = tree.name;
  lines.push(`# bash completion for ${name}`);
  lines.push(`# Generated by: ${name} completion bash`);
  lines.push('');
  lines.push(`_${name}_completions() {`);
  lines.push('  local cur prev words cword');
  lines.push(
    '  if type _init_completion &>/dev/null; then _init_completion || return; else',
  );
  // biome-ignore lint/suspicious/noTemplateCurlyInString: bash syntax
  lines.push('    cur="${COMP_WORDS[COMP_CWORD]}"');
  // biome-ignore lint/suspicious/noTemplateCurlyInString: bash syntax
  lines.push('    prev="${COMP_WORDS[COMP_CWORD-1]}"');
  // biome-ignore lint/suspicious/noTemplateCurlyInString: bash syntax
  lines.push('    words=("${COMP_WORDS[@]}")');
  lines.push('    cword=$COMP_CWORD');
  lines.push('  fi');
  lines.push('');

  if (choiceOptions.size > 0) {
    lines.push('  case "$prev" in');
    for (const [flag, choices] of choiceOptions) {
      lines.push(
        `    ${flag}) COMPREPLY=($(compgen -W "${choices.join(' ')}" -- "$cur")); return ;;`,
      );
    }
    lines.push('  esac');
    lines.push('');
  }

  const valueFlags = collectValueFlags(tree);
  const valueFlagPattern = valueFlags.join('|');

  lines.push('  local cmd_path=""');
  lines.push('  local i=1');
  lines.push('  while [ $i -lt $cword ]; do');
  // biome-ignore lint/suspicious/noTemplateCurlyInString: bash syntax
  lines.push('    case "${words[$i]}" in');
  if (valueFlagPattern) {
    lines.push(`      ${valueFlagPattern}) i=$((i + 1)) ;;`);
  }
  lines.push('      -*) ;;');
  // biome-ignore lint/suspicious/noTemplateCurlyInString: bash syntax
  lines.push('      *) cmd_path="${cmd_path:+$cmd_path }${words[$i]}" ;;');
  lines.push('    esac');
  lines.push('    i=$((i + 1))');
  lines.push('  done');
  lines.push('');
  lines.push('  if [[ "$cur" == -* ]]; then');
  lines.push('    case "$cmd_path" in');

  for (const entry of childEntries) {
    const optFlags = entry.options
      .map((o) => o.long)
      .filter(Boolean)
      .join(' ');
    if (optFlags) {
      const key = entry.path.replace(`${tree.name} `, '');
      lines.push(
        `      "${key}") COMPREPLY=($(compgen -W "${optFlags}" -- "$cur")) ;;`,
      );
    }
  }
  {
    const rootFlags = globalOpts
      .map((o) => o.long)
      .filter(Boolean)
      .join(' ');
    if (rootFlags) {
      lines.push(
        `      *) COMPREPLY=($(compgen -W "${rootFlags}" -- "$cur")) ;;`,
      );
    }
  }

  lines.push('    esac');
  lines.push('    return');
  lines.push('  fi');
  lines.push('');
  lines.push('  case "$cmd_path" in');

  for (const entry of childEntries) {
    if (entry.subcommands.length === 0) {
      continue;
    }
    const subs = entry.subcommands.map((s) => s.name).join(' ');
    const key = entry.path.replace(`${tree.name} `, '');
    lines.push(
      `    "${key}") COMPREPLY=($(compgen -W "${subs}" -- "$cur")) ;;`,
    );
  }

  {
    const rootSubs = entries[0].subcommands.map((s) => s.name).join(' ');
    lines.push(
      `    "${tree.name}") COMPREPLY=($(compgen -W "${rootSubs}" -- "$cur")) ;;`,
    );
    lines.push(`    *) COMPREPLY=($(compgen -W "${rootSubs}" -- "$cur")) ;;`);
  }

  lines.push('  esac');
  lines.push('}');
  lines.push('');
  lines.push(`complete -F _${name}_completions ${name}`);

  return lines.join('\n');
}

// --- Zsh ---

export function generateZshCompletion(tree: CommandNode): string {
  const globalOpts = tree.options;
  const entries = flattenTree(tree, '', []);
  const childEntries = entries.slice(1);

  const choiceOptions: Map<string, string[]> = new Map();
  for (const entry of entries) {
    for (const opt of entry.options) {
      if (opt.choices && opt.long) {
        choiceOptions.set(opt.long, opt.choices);
      }
    }
  }

  const lines: string[] = [];
  const name = tree.name;
  lines.push(`#compdef ${name}`);
  lines.push(`# zsh completion for ${name}`);
  lines.push(`# Generated by: ${name} completion zsh`);
  lines.push('');
  lines.push(`_${name}() {`);
  lines.push('  local cur prev cmd_path');
  // biome-ignore lint/suspicious/noTemplateCurlyInString: zsh syntax
  lines.push('  cur="${words[$CURRENT]}"');
  // biome-ignore lint/suspicious/noTemplateCurlyInString: zsh syntax
  lines.push('  prev="${words[$CURRENT-1]}"');
  lines.push('');

  if (choiceOptions.size > 0) {
    lines.push('  case "$prev" in');
    for (const [flag, choices] of choiceOptions) {
      lines.push(`    ${flag}) compadd -- ${choices.join(' ')}; return ;;`);
    }
    lines.push('  esac');
    lines.push('');
  }

  const valueFlags = collectValueFlags(tree);
  const valueFlagPattern = valueFlags.join('|');

  lines.push('  cmd_path=""');
  lines.push('  for ((i=2; i < CURRENT; i++)); do');
  // biome-ignore lint/suspicious/noTemplateCurlyInString: zsh syntax
  lines.push('    case "${words[$i]}" in');
  if (valueFlagPattern) {
    lines.push(`      ${valueFlagPattern}) ((i++)) ;;`);
  }
  lines.push('      -*) ;;');
  // biome-ignore lint/suspicious/noTemplateCurlyInString: zsh syntax
  lines.push('      *) cmd_path="${cmd_path:+$cmd_path }${words[$i]}" ;;');
  lines.push('    esac');
  lines.push('  done');
  lines.push('');
  lines.push('  if [[ "$cur" == -* ]]; then');
  lines.push('    case "$cmd_path" in');

  for (const entry of childEntries) {
    const optFlags = entry.options
      .map((o) => o.long)
      .filter(Boolean)
      .join(' ');
    if (optFlags) {
      const key = entry.path.replace(`${tree.name} `, '');
      lines.push(`      "${key}") compadd -- ${optFlags} ;;`);
    }
  }
  {
    const rootFlags = globalOpts
      .map((o) => o.long)
      .filter(Boolean)
      .join(' ');
    if (rootFlags) {
      lines.push(`      *) compadd -- ${rootFlags} ;;`);
    }
  }

  lines.push('    esac');
  lines.push('    return');
  lines.push('  fi');
  lines.push('');
  lines.push('  case "$cmd_path" in');

  for (const entry of childEntries) {
    if (entry.subcommands.length === 0) {
      continue;
    }
    const subs = entry.subcommands.map((s) => s.name).join(' ');
    const key = entry.path.replace(`${tree.name} `, '');
    lines.push(`    "${key}") compadd -- ${subs} ;;`);
  }

  {
    const rootSubs = entries[0].subcommands.map((s) => s.name).join(' ');
    lines.push(`    *) compadd -- ${rootSubs} ;;`);
  }

  lines.push('  esac');
  lines.push('}');
  lines.push('');
  lines.push(`compdef _${name} ${name}`);

  return lines.join('\n');
}

// --- Fish ---

export function generateFishCompletion(tree: CommandNode): string {
  const name = tree.name;
  const entries = flattenTree(tree, '', []);
  const lines: string[] = [];
  lines.push(`# fish completion for ${name}`);
  lines.push(`# Generated by: ${name} completion fish`);
  lines.push('');

  const rootEntry = entries[0];
  for (const sub of rootEntry.subcommands) {
    lines.push(
      `complete -c ${name} -n "__fish_use_subcommand" -a "${sub.name}" -d "${escapeFish(sub.description)}"`,
    );
  }

  for (const opt of tree.options) {
    if (opt.long) {
      const flag = opt.long.replace('--', '');
      let line = `complete -c ${name} -l "${flag}"`;
      if (opt.short) {
        line += ` -s "${opt.short.replace('-', '')}"`;
      }
      if (opt.takesValue) {
        line += ' -r';
      }
      if (opt.choices) {
        line += ` -a "${opt.choices.join(' ')}"`;
      }
      line += ` -d "${escapeFish(opt.description)}"`;
      lines.push(line);
    }
  }

  for (const entry of entries.slice(1)) {
    const parts = entry.path.split(' ').slice(1);
    const parentCmd = parts[parts.length - 1];
    const condition = `__fish_seen_subcommand_from ${parentCmd}`;

    for (const sub of entry.subcommands) {
      lines.push(
        `complete -c ${name} -n "${condition}" -a "${sub.name}" -d "${escapeFish(sub.description)}"`,
      );
    }

    for (const opt of entry.options) {
      if (opt.long) {
        const flag = opt.long.replace('--', '');
        let line = `complete -c ${name} -n "${condition}" -l "${flag}"`;
        if (opt.short) {
          line += ` -s "${opt.short.replace('-', '')}"`;
        }
        if (opt.takesValue) {
          line += ' -r';
        }
        if (opt.choices) {
          line += ` -a "${opt.choices.join(' ')}"`;
        }
        line += ` -d "${escapeFish(opt.description)}"`;
        lines.push(line);
      }
    }
  }

  return lines.join('\n');
}

function escapeFish(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

// --- PowerShell ---

export function generatePowerShellCompletion(tree: CommandNode): string {
  const name = tree.name;
  const entries = flattenTree(tree, '', []);

  const lines: string[] = [];
  lines.push(`# PowerShell completion for ${name}`);
  lines.push(`# Generated by: ${name} completion powershell`);
  lines.push('');
  lines.push(
    `Register-ArgumentCompleter -Native -CommandName ${name} -ScriptBlock {`,
  );
  lines.push('  param($wordToComplete, $commandAst, $cursorPosition)');
  lines.push('');
  lines.push(
    '  $words = $commandAst.ToString().Substring(0, $cursorPosition) -split "\\s+"',
  );
  const valueFlags = collectValueFlags(tree);
  const valueFlagsList = valueFlags.map((f) => `"${f}"`).join(', ');

  lines.push('  $cmdPath = @()');
  lines.push(`  $valueFlags = @(${valueFlagsList})`);
  lines.push('  for ($i = 1; $i -lt $words.Count - 1; $i++) {');
  lines.push('    if ($valueFlags -contains $words[$i]) { $i++; continue }');
  lines.push('    if ($words[$i] -notlike "-*") { $cmdPath += $words[$i] }');
  lines.push('  }');
  lines.push('  $joined = $cmdPath -join " "');
  lines.push('  $cur = $words[-1]');
  lines.push('  if ($words.Count -eq 1) { $cur = "" }');
  lines.push('');
  lines.push('  $prev = if ($words.Count -ge 2) { $words[-2] } else { "" }');
  lines.push('');

  const choiceOptions: Map<string, string[]> = new Map();
  for (const entry of entries) {
    for (const opt of entry.options) {
      if (opt.choices && opt.long) {
        choiceOptions.set(opt.long, opt.choices);
      }
    }
  }

  if (choiceOptions.size > 0) {
    lines.push('  switch ($prev) {');
    for (const [flag, choices] of choiceOptions) {
      const choicesList = choices.map((c) => `"${c}"`).join(', ');
      lines.push(
        `    "${flag}" { @(${choicesList}) | Where-Object { $_ -like "$cur*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_) }; return }`,
      );
    }
    lines.push('  }');
    lines.push('');
  }

  lines.push('  $completions = @()');
  lines.push('');
  lines.push('  if ($cur -like "-*") {');
  lines.push('    $opts = switch ($joined) {');

  const childEntries = entries.slice(1);
  for (const entry of childEntries) {
    const optFlags = entry.options
      .map((o) => o.long)
      .filter(Boolean)
      .map((f) => `"${f}"`)
      .join(', ');
    if (optFlags) {
      const key = entry.path.replace(`${tree.name} `, '');
      lines.push(`      "${key}" { @(${optFlags}) }`);
    }
  }
  {
    const rootFlags = tree.options
      .map((o) => o.long)
      .filter(Boolean)
      .map((f) => `"${f}"`)
      .join(', ');
    if (rootFlags) {
      lines.push(`      default { @(${rootFlags}) }`);
    }
  }

  lines.push('    }');
  lines.push(
    '    $completions = $opts | Where-Object { $_ -like "$cur*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_) }',
  );
  lines.push('  } else {');
  lines.push('    $subs = switch ($joined) {');

  for (const entry of childEntries) {
    if (entry.subcommands.length === 0) {
      continue;
    }
    const subs = entry.subcommands.map((s) => `"${s.name}"`).join(', ');
    const key = entry.path.replace(`${tree.name} `, '');
    lines.push(`      "${key}" { @(${subs}) }`);
  }
  {
    const rootSubs = entries[0].subcommands
      .map((s) => `"${s.name}"`)
      .join(', ');
    lines.push(`      default { @(${rootSubs}) }`);
  }

  lines.push('    }');
  lines.push(
    '    $completions = $subs | Where-Object { $_ -like "$cur*" } | ForEach-Object { [System.Management.Automation.CompletionResult]::new($_) }',
  );
  lines.push('  }');
  lines.push('');
  lines.push('  $completions');
  lines.push('}');

  return lines.join('\n');
}
